/*Construção do BD
Dupla: Bárbara e Daiane */
CREATE DATABASE mapa_escola;
USE mapa_escola;

CREATE TABLE CIDADE(
    CodCidade INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (CodCidade)
);

CREATE TABLE DISCIPLINA(
    CodDisciplina INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (CodDisciplina)
);

CREATE TABLE PESSOA(
    CodPessoa INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CodCidade INT UNSIGNED NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Telefone VARCHAR(20),
    PRIMARY KEY (CodPessoa),
    CONSTRAINT fk_pessoa_reside FOREIGN KEY (CodCidade) REFERENCES CIDADE(CodCidade)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PROFESSOR(
    CodPessoa INT UNSIGNED NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    Titulacao VARCHAR (50),
    PRIMARY KEY (CodPessoa),
    CONSTRAINT uk_prof_rg UNIQUE KEY (rg),
    CONSTRAINT uk_prof_cpf UNIQUE KEY (cpf),
    CONSTRAINT fk_prof_pessoa FOREIGN KEY (CodPessoa) REFERENCES PESSOA(CodPessoa)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ESCOLA(
    CodEscola INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CodCidade INT UNSIGNED NOT NULL,
    CodPessoa INT UNSIGNED NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (CodEscola),
    CONSTRAINT uk_escola_prof_pessoa UNIQUE KEY (CodPessoa),
    CONSTRAINT fk_escola_cidade FOREIGN KEY (CodCidade) REFERENCES CIDADE(CodCidade),
    CONSTRAINT fk_escola_professor FOREIGN KEY (CodPessoa) REFERENCES PROFESSOR(CodPessoa)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE TURMA(
    CodTurma INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CodEscola INT UNSIGNED NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (CodTurma),
    CONSTRAINT fk_turma_escola FOREIGN KEY (CodEscola) REFERENCES ESCOLA(CodEscola)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ALUNO(
    CodPessoa INT UNSIGNED NOT NULL,
    CodTurma INT UNSIGNED NOT NULL,
    Matricula INT UNSIGNED NOT NULL,
    Data_Nascimento DATE,
    PRIMARY KEY (CodPessoa),
    CONSTRAINT uk_pessoa_aluno UNIQUE KEY (Matricula),
    CONSTRAINT fk_pessoa_aluno FOREIGN KEY (CodPessoa) REFERENCES PESSOA(CodPessoa)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_aluno_turma FOREIGN KEY (CodTurma) REFERENCES TURMA(CodTurma)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CONTATO(
    Nome VARCHAR(50) NOT NULL DEFAULT ' ',
    CodPessoa INT UNSIGNED NOT NULL,
    Telefone VARCHAR(20),
    PRIMARY KEY (Nome, CodPessoa),
    CONSTRAINT fk_contato_aluno FOREIGN KEY (CodPessoa) REFERENCES ALUNO(CodPessoa)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE MINISTRA_DISCIPLINA(
    CodPessoa INT UNSIGNED NOT NULL,
    CodDisciplina INT UNSIGNED NOT NULL,
    PRIMARY KEY (CodPessoa, CodDisciplina),
    CONSTRAINT fk_ministra_professor FOREIGN KEY (CodPessoa) REFERENCES PROFESSOR(CodPessoa)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ministra_disciplina FOREIGN KEY (CodDisciplina) REFERENCES DISCIPLINA(CodDisciplina)
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE MINISTRA_TURMA(
    CodPessoa INT UNSIGNED NOT NULL,
    CodDisciplina INT UNSIGNED NOT NULL,
    CodTurma INT UNSIGNED NOT NULL,
    PRIMARY KEY (CodPessoa, CodDisciplina, CodTurma),
    CONSTRAINT fk_turma_disciplina FOREIGN KEY (CodPessoa, CodDisciplina) REFERENCES MINISTRA_DISCIPLINA(CodPessoa, CodDisciplina)
    ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_ministra_turma FOREIGN KEY (CodTurma) REFERENCES TURMA(CodTurma)
    ON UPDATE CASCADE ON DELETE CASCADE
);
